### PR TITLE
Adding failure middleware capabilities.

### PR DESCRIPTION
**Pull request by risseraka**
Added in README and tests.

### CODE REVIEW

**Comment by elliotttf** [comment]
Thanks for the contribution, can you explain when exactly you're needing this? I've typically handled needing an else case like this:

``` javascript
app.use(
  conditional(
    req => req.condition
    (req, res) => {
      // The middleware chain ends here since `next` is not executed.
      res.status(204).end();
    }
  ),
  (req, res, next) => {
    // This becomes the otherwise.
    res.json({});
  }
);
```

**Comment by risseraka** [comment]
@elliotttf 

Thanks for reviewing this.

Here's my typical usage of `conditional`:

```
app.get(
  '/users',
  conditional(
    // condition is "have a `q` query parameter"
    req => req.query.q,
    // true conditional
    (req, res, next) => search(req.query.q, (err, results) => {
      if (err) return next(err);
      req.state.results = results;
    }),
    // false conditional
    (req, res, next) => fetchAll(req.query.q, (err, results) => {
      if (err) return next(err);
      req.state.results = results;
    })
  ),
  (req, res) => {
    // Always pass through this final step
    const results = templatedTransform(req.state.results);
    res.json(results);
  }
);
```

Hope that helps understanding my use case.

If you have other suggestions to handle query parameters which have filtering behaviors, let me know.

Cheers.

**Comment by elliotttf** [comment]
That makes sense. Now that we've got two potential middlewares perhaps the parameters should be renamed to something like `success` and `fail`.

**Comment by risseraka** [comment]
I've updated the code and README accordingly to your wishes.
Let me know if I've missed anything.
Cheers.

**Comment by elliotttf** [comment]
Awesome, thanks for your contribution! I'll cut a release when I'm back at a keyboard. :beers:

**Comment by risseraka** [comment]
My pleasure, thanks for this module. :ok_hand:

**Pull request merged**
